networks:
  traefik-exposed:
    external: true

services:
  homepage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homepage
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http, https"
      - "traefik.http.routers.homepage.rule=Host(`tvdermeer.nl`)"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=production"
      - "traefik.http.services.homepage.loadbalancer.server.port=80"

    # If not using Traefik, uncomment to expose directly:
    ports:
      - "3000:80"
    networks:
    - traefik-exposed
