export const mockPosts = [
  {
    title: "Test Post One",
    slug: "test-post-one",
    description: "First test post description",
    date: "2026-01-15",
    updated: undefined,
    tags: ["ai", "golf"],
    published: true,
    content: "<p>Test content one</p>",
    metadata: {},
    excerpt: "First test post excerpt",
    permalink: "/blog/test-post-one",
  },
  {
    title: "Test Post Two",
    slug: "test-post-two",
    description: "Second test post description",
    date: "2026-02-20",
    updated: undefined,
    tags: ["ai"],
    published: true,
    content: "<p>Test content two</p>",
    metadata: {},
    excerpt: "Second test post excerpt",
    permalink: "/blog/test-post-two",
  },
  {
    title: "Draft Post",
    slug: "draft-post",
    description: "An unpublished draft",
    date: "2026-03-01",
    updated: undefined,
    tags: [],
    published: false,
    content: "<p>Draft content</p>",
    metadata: {},
    excerpt: "Draft excerpt",
    permalink: "/blog/draft-post",
  },
];
